"""create metrics table

Revision ID: 0dc63c4bc11b
Revises: 
Create Date: 2026-03-24 11:39:13.524098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '0dc63c4bc11b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = {column['name'] for column in inspector.get_columns('tb_metrics_snapshots')}

    if 'metric_at' not in columns:
        op.add_column('tb_metrics_snapshots', sa.Column('metric_at', sa.TIMESTAMP(), nullable=False))
    if 'source_alias' not in columns:
        op.add_column('tb_metrics_snapshots', sa.Column('source_alias', sa.Text(), nullable=True))
    op.alter_column('tb_metrics_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tb_metrics_snapshots', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('tb_metrics_snapshots', 'profit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('tb_metrics_snapshots', 'roi',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=8, scale=4),
               nullable=True)
    if 'id' in columns:
        try:
            op.create_index(op.f('ix_tb_metrics_snapshots_id'), 'tb_metrics_snapshots', ['id'], unique=False)
        except Exception:
            pass
    if 'metric_ate' in columns:
        op.drop_column('tb_metrics_snapshots', 'metric_ate')
    if 'source' in columns:
        op.drop_column('tb_metrics_snapshots', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = {column['name'] for column in inspector.get_columns('tb_metrics_snapshots')}

    if 'source' not in columns:
        op.add_column('tb_metrics_snapshots', sa.Column('source', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    if 'metric_ate' not in columns:
        op.add_column('tb_metrics_snapshots', sa.Column('metric_ate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    try:
        op.drop_index(op.f('ix_tb_metrics_snapshots_id'), table_name='tb_metrics_snapshots')
    except Exception:
        pass
    op.alter_column('tb_metrics_snapshots', 'roi',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('tb_metrics_snapshots', 'profit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('tb_metrics_snapshots', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('tb_metrics_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    if 'source_alias' in columns:
        op.drop_column('tb_metrics_snapshots', 'source_alias')
    if 'metric_at' in columns:
        op.drop_column('tb_metrics_snapshots', 'metric_at')
    # ### end Alembic commands ###
