"""adicionando squad e revenue

Revision ID: 3e1274766ca9
Revises: cf263002b989
Create Date: 2026-03-27 13:09:27.816419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1274766ca9'
down_revision: Union[str, Sequence[str], None] = 'cf263002b989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_metrics_snapshots', sa.Column('squad', sa.Text(), nullable=True))
    op.add_column('tb_metrics_snapshots', sa.Column('revenue', sa.Numeric(precision=8, scale=2), nullable=True))
    op.drop_column('tb_metrics_snapshots', 'source_alias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_metrics_snapshots', sa.Column('source_alias', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tb_metrics_snapshots', 'revenue')
    op.drop_column('tb_metrics_snapshots', 'squad')
    # ### end Alembic commands ###
