"""creating the checout conversion

Revision ID: f53e3a2f1094
Revises: 9b2d3f4a6c11
Create Date: 2026-03-30 15:45:22.352462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53e3a2f1094'
down_revision: Union[str, Sequence[str], None] = '9b2d3f4a6c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_metrics_snapshots', sa.Column('checkout_conversion', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_metrics_snapshots', 'checkout_conversion')
    # ### end Alembic commands ###
